### ISSUE TITLE
Under which license is this published?

### ISSUE THREAD

**Issue by pluk77** [ReneeMaxwell/TOCLegendWidget#1]
We would like to use this code in an application, but the project / code does not contain a license agreement. 

Could you perhaps clarify under which license we can use this? If you do not know which license to choose, maybe this site can assist you: http://choosealicense.com/

Some more details on what it means if you do not specifically add a license: https://help.github.com/articles/open-source-licensing/

Marcel

**Comment by ReneeMaxwell** [comment]
Marcel,

Thank you for your interest, I had forgotten about this project. I have added a license file for the MIT License.

Renee

**Comment by pluk77** [comment]
Thanks a lot for your speedy response and for choosing such an open license.
